print("Welcome to the Band Name Generator")
city_name = input("What is the city you lived in? \n")
# print(city_name)
pet_name = input("What's your pet's name \n")
# print(pet_name)
print("Your band name could be "+city_name+""+pet_name)